Inf
NA
NaN
is.numeric(Inf)
is.character(Inf)
is.logical(Inf)
is.integer(Inf)
is.complex(Inf)
class(Inf)
mode(Inf)
storage.mode(Inf)
class(NA)
mode(NA)
storage.mode(NA)
class(NaN)
mode(NaN)
storage.mode(NaN)
gender<-factor(c("dog","cat","hamster","goldfish"))
sample(gender,1000,replace=TRUE)
apple<-1
cabbaje<-2
carrot<-3
tomato<-4
ls(pattern="a")
