tan(1:1000)
atan(1:1000)
c(1:1000)
x<-c(1:1000)     
tan(1/x)
atan(1/x)
y<-atan(1/x)
1/tan(y)
z<-1/tan(y)
x==z
identical(x,z)
all.equal(x,z)
all.equal(x,z,0)
true_and_missing<-NA
false_and_missing<-FALSE
mixed<-TRUE
any(true_and_missing>0)
any(false_and_missing>0)
any(mixed>0)
all(true_and_missing>0)
all(false_and_missing>0)
all(mixed>0)
